version: "3"
services:
  userservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '81:80'
      - '9000:9000'
    environment: 
      - API_KEY=sdfsdfsdf

networks: 
  default: 
    external: 
      name: scicat